name: firelamp
description: A flutter package to support CMS(Content Management System) functionalities like user management, forum management, and more for building apps like social apps, shopping apps.
version: 0.1.0
homepage: https://github.com/thruthesky/firelamp

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.1.1
  firebase_auth: ^1.1.4
  cloud_firestore: ^2.1.0
  firebase_messaging: ^9.1.4

  # intl: ^0.16.0
  intl: ^0.17.0

  path: ^1.8.0

  # get: ^3.26.0
  get: ^4.1.4

  # shared_preferences: 0.5.10
  shared_preferences: ^2.0.5

  # widgets dependencies
  photo_view: ^0.11.1
  cached_network_image: ^3.0.0
  flutter_staggered_grid_view: ^0.4.0

  rxdart: ^0.27.0
  # dio: ^3.0.10
  dio: ^4.0.0
  http_parser: ^4.0.0

  scrollable_positioned_list: ^0.2.0-nullsafety.0

  # patch version for prevening app crash on iOS.
  # image_picker: ^0.6.7+22
  image_picker: ^0.7.5

  # age: ^0.0.1

  # Chat room. Scroll adjustment when keypad is open.
  # flutter_keyboard_visibility: ^4.0.3
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
