name: firelamp
description: A flutter package to support CMS(Content Management System) functionalities like user management, forum management, and more for building apps like social apps, shopping apps.
version: 0.0.8
homepage: https://github.com/thruthesky/firelamp

environment:
  sdk: ">=2.10.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # firebase_core: "^0.7.0"
  # firebase_auth: "^0.20.1"
  # cloud_firestore: "^0.16.0+1"
  # firebase_messaging: "^8.0.0-dev.15"

  firebase_core: ^1.0.3
  firebase_auth: ^1.1.0
  cloud_firestore: ^1.0.5
  firebase_messaging: ^9.1.1

  # intl: ^0.16.0
  intl: ^0.17.0

  path: ^1.8.0

  # get: ^3.26.0
  get: ^4.1.4

  # shared_preferences: 0.5.10
  shared_preferences: ^2.0.5

  # widgets dependencies
  photo_view: ^0.11.1
  cached_network_image: ^2.5.0
  flutter_staggered_grid_view: ^0.3.4
  flutter_icons: ^1.1.0

  rxdart: ^0.25.0
  # dio: ^3.0.10
  dio: ^4.0.0
  http_parser: ^4.0.0

  scrollable_positioned_list: ^0.1.8

  # patch version for prevening app crash on iOS.
  # image_picker: ^0.6.7+22
  image_picker: ^0.7.4

  age: ^0.0.1

  # Chat room. Scroll adjustment when keypad is open.
  # flutter_keyboard_visibility: ^4.0.3

  flutter_linkify: ^5.0.2
  url_launcher: ^6.0.6

  permission_handler: ^6.0.1
  fluttertoast: ^8.0.1-nullsafety.0
  image_gallery_saver: ^1.6.9
  video_player: ^2.1.6


  dotted_line: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
