name: firelamp
description: A flutter package to support CMS(Content Management System) functionalities like user management, forum management, and more for building apps like social apps, shopping apps.
version: 0.0.2
homepage: https://github.com/thruthesky/firelamp

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: "0.7.0"
  firebase_database: "^6.0.0"
  get: ^3.24.0
  get_storage: ^1.4.0

  rxdart: ^0.25.0
  dio: ^3.0.10

  scrollable_positioned_list: ^0.1.8

  age: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
